### ISSUE TITLE
AttributeError: module 'config' has no attribute 'stashbox_target'

### ISSUE THREAD

**Issue by cloudstrife112** [stg-annon/StashBulkScrape#1]
23-01-29 08:54:37
Error   
Plugin returned error: exit status 1
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape] AttributeError: module 'config' has no attribute 'stashbox_target'
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape]     sbox_config.update(stash.get_stashbox_connection(config.stashbox_target))
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 23, in main
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape]     main()
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 57, in <module>
2023-01-29 08:54:37
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):

**Comment by stg-annon** [comment]
looks like you haven't created the config file with like from the [example](https://github.com/stg-annon/StashBulkScrape/blob/a9f20124218305fc3ab9281cea27674a7d0088db/example_config.py#L26)

**Comment by cloudstrife112** [comment]
I have just copy the whole plugin folder StashBulkScrape to plugins. and this is my config so i realy dont know why it isnt working: from utils.stash_types import StashItem
```
# Create missing performers/tags/studios/movies
# Default: False (Prevent Stash from getting flooded with weird values)
create_missing_performers = True
create_missing_tags = False
create_missing_studios = True
create_missing_movies = True

# url scrape config, comment out unwanted scrapes
BULK_URL = [
   StashItem.SCENE,
   StashItem.GALLERY,
   StashItem.MOVIE,
   # StashItem.PERFORMER,
]
# fragment scrape config, comment out unwanted scrapes
FRAGMENT_SCRAPE = [
   StashItem.SCENE,
   StashItem.GALLERY,
   StashItem.MOVIE,
   # StashItem.PERFORMER,
]

# stashbox scrape config
stashbox_target = "stashdb.org"
stashbox_submit_fingerprints = False

# Delay between web requests (seconds)
EXTERNAL_WEB_REQUEST_DELAY = 3.0

# tag to add to stash items that are not up to date with stashbox_target
STASHBOX_UPDATE_AVAILABLE_TAG = "STASHBOX_UPDATE"
# Name of the tag, that will be used for selecting scenes for bulk url scraping
BULK_URL_CONTROL_TAG = "blk_scrape_url"
# stash box control tag
BULK_STASHBOX_CONTROL_TAG = "blk_scrape_stashbox"

# Prefix of all fragment scraper tags
SCRAPE_WITH_PREFIX = "blk_scrape_"
```

i have installed the requirements,

**Comment by stg-annon** [comment]
that is the `example_config.py` did you rename it to `config.py` before running? the script will be looking for a file name `config.py`

**Comment by cloudstrife112** [comment]
yes i did rename it now to config,py, but then I get this : 2023-02-05 08:35:31
Error   
Plugin returned error: exit status 1
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape] ModuleNotFoundError: No module named 'utils.stash_types'
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape]     from utils.stash_types import StashItem
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\bulkScrape\config.py", line 1, in <module>
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape]     import config
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\bulkScrape\main.py", line 3, in <module>
2023-02-05 08:35:31
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):
2023-02-05 08:35:31
Error   
Plugin returned error: exit status 1

**Comment by stg-annon** [comment]
haven't touched this plugin in a while you'll want to change [this line](https://github.com/stg-annon/StashBulkScrape/commit/481f0c5379975aadc74b94089a9ce29f7b5d873c) in the config file

**Comment by cloudstrife112** [comment]
3-02-06 12:26:38
Error   
Plugin returned error: exit status 1
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] AttributeError: 'NoneType' object has no attribute 'keys'
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     queryType = list(r.keys())[0]
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "C:\Users\tuink\AppData\Local\Programs\Python\Python310\lib\site-packages\stashapi\classes.py", line 217, in _callGraphQLRecursive
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     return self._callGraphQLRecursive(query, variables)
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "C:\Users\tuink\AppData\Local\Programs\Python\Python310\lib\site-packages\stashapi\classes.py", line 180, in _callGraphQL
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     result = self._callGraphQL(query, variables)
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "C:\Users\tuink\AppData\Local\Programs\Python\Python310\lib\site-packages\stashapi\stashapp.py", line 953, in find_scenes
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     scenes = self.stash.find_scenes(f={
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 83, in bulk_url_scrape
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     scraper.bulk_url_scrape()
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 41, in main
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]     main()
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 57, in <module>
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 15, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 15, 'files', 0, 'created_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 81, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 90, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 89, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 65, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 143, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 74, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 61, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 139, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 142, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 150, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 87, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 151, 'files', 0, 'updated_at']
2023-02-06 12:26:38
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 73, 'files', 0, 'updated_at']

**Comment by cloudstrife112** [comment]
I have dev stash installed, can this be the problem?

**Comment by stg-annon** [comment]
> I have dev stash installed, can this be the problem?

It shouldn't be 

This latest log is a bit weird I'll need to do some debugging on my end, I'll also be updating `stashapp-tools` to hopefully produce some more helpful logs for this particular edge case

**Comment by stg-annon** [comment]
@cloudstrife112 I updated stashapp-tools to 0.2.19 try updating to that, I'd be curious what output you would get with that

**Comment by cloudstrife112** [comment]
Now I getting this 23-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] Variables: {'filter': {'per_page': 1000, 'q': '', 'page': 1}, 'scene_filter': {'tags': {'value': ['5270'], 'depth': 0, 'modifier': 'INCLUDES'}, 'url': {'value': '', 'modifier': 'NOT_NULL'}}}
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] scenes { id }
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] scene_count
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] back_image_path
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] front_image_path
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] updated_at
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] created_at
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] url
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] synopsis
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] director
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] studio { id }
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] rating100
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] rating
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] date
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] duration
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] aliases
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] name
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] checksum
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] id
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] fragment Movie on Movie {
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] value
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] type
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] fragment Fingerprint on Fingerprint {
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] caption
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] interactive_heatmap
2023-02-09 12:49:00
Error   
[Plugin / Bulk Scrape] funscript

**Comment by cloudstrife112** [comment]
I have just copied these files : https://github.com/stg-annon/stashapi/tree/51122190fa990f55cac83bf8b6f74d22b2e691f2
in the folder : C:\Users\tuink\AppData\Local\Programs\Python\Python310\Lib\site-packages\stashapi

but when I do command : pip install stashapp-tools It gives me that :Requirement already satisfied: stashapp-tools in c:\users\tuink\appdata\local\programs\python\python310\lib\site-packages (0.2.18). but this is not 0.2.19.

**Comment by cloudstrife112** [comment]
When I do scrape URL:
Now I getting this
```
23-02-09 12:49:00
Error
[Plugin / Bulk Scrape] Variables: {'filter': {'per_page': 1000, 'q': '', 'page': 1}, 'scene_filter': {'tags': {'value': ['5270'], 'depth': 0, 'modifier': 'INCLUDES'}, 'url': {'value': '', 'modifier': 'NOT_NULL'}}}
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] scenes { id }
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] scene_count
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] back_image_path
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] front_image_path
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] updated_at
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] created_at
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] url
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] synopsis
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] director
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] studio { id }
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] rating100
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] rating
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] date
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] duration
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] aliases
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] name
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] checksum
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] id
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] fragment Movie on Movie {
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] value
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] type
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] fragment Fingerprint on Fingerprint {
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] }
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] caption
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] interactive_heatmap
2023-02-09 12:49:00
Error
[Plugin / Bulk Scrape] funscript
```

When I do fragment scrape: 
```
23-02-09 12:56:53
Error   
Plugin returned error: exit status 1
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape] AttributeError: 'StashInterface' object has no attribute 'list_item_scrapers'. Did you mean: 'list_scene_scrapers'?
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]     for s in self.stash.list_item_scrapers(stash_item, ScrapeType.FRAGMENT):
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 234, in list_all_fragment_tags
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]     for scraper_id, stash_items in self.list_all_fragment_tags().items():
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 151, in bulk_fragment_scrape
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]     scraper.bulk_fragment_scrape()
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 43, in main
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]     main()
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 57, in <module>
2023-02-09 12:56:53
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):
2023-02-09 12:56:36
Error   
Plugin returned error: exit status 1
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape] AttributeError: 'StashInterface' object has no attribute 'list_item_scrapers'. Did you mean: 'list_scene_scrapers'?
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]     for s in self.stash.list_item_scrapers(stash_item, ScrapeType.FRAGMENT):
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 234, in list_all_fragment_tags
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]     for scraper_id, stash_items in self.list_all_fragment_tags().items():
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 151, in bulk_fragment_scrape
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]     scraper.bulk_fragment_scrape()
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\main.py", line 43, in main
2023-02-09 12:56:36
Error   
[Plugin / Bulk Scrape]     main()
```

**Comment by stg-annon** [comment]
@cloudstrife112 the errors with `Fragment Scrape` should be fixed as for the issues you're having with `URL Scrape` ill need some more info that whole log is just the query that was sent to the api

you'll need to update both stashapi and this plugin from git again

**Comment by cloudstrife112** [comment]
I have now installed stashapp-tools 0.2.19 and updated the stashapi and your plugin stashbulk. still getting this 
2023-02-11 08:13:42
Error   
Plugin returned error: exit status 1
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape] AttributeError: 'list' object has no attribute 'get'
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]        ^^^^^^^^^^^^^^^
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]     if stash_items.get(StashItem.SCENE):
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 150, in bulk_fragment_scrape
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]     scraper.bulk_fragment_scrape()
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main/main.py", line 43, in main
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]     main()
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape]   File "Z:\Stash\plugins\StashBulkScrape-main/main.py", line 57, in <module>
2023-02-11 08:13:42
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):

**Comment by stg-annon** [comment]
working through some changes with the fragment side of things, should be working now @cloudstrife112

**Comment by cloudstrife112** [comment]
> working through some changes with the fragment side of things, should be working now @cloudstrife112

thanks for working on this. but still I am getting this: 
URL SCRAPE:
23-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] 200 query failed.
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GQL data response is null
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 55, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 51, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 53, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 54, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 12, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 26, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 50, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 49, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 52, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 25, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 11, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 24, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 23, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 10, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 9, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 22, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 21, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 20, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 19, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 48, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 46, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 47, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 45, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 38, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 8, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 37, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 0, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 7, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 17, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 16, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 15, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 14, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 35, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 13, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 34, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 1, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 33, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 32, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 44, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 31, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 43, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 30, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 42, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 29, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 41, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 28, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 40, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 5, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 6, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 27, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 36, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 18, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 2, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 4, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 3, 'file']
2023-02-14 08:29:27
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: must not be null ['findScenes', 'scenes', 39, 'file']
2023-02-14 08:29:26
Info    
[Plugin / Bulk Scrape] Progress bar will reset for each item type (scene, movie, ect.)
2023-02-14 08:29:26
Info    
[Plugin / Bulk Scrape] Performing Bulk URL Scrape



FRAGMENT SCRAPE:
2023-02-14 08:30:11
Error   
[Plugin / Bulk Scrape] 200 query failed.
2023-02-14 08:30:11
Error   
[Plugin / Bulk Scrape] GQL data response is null
2023-02-14 08:30:11
Error   
[Plugin / Bulk Scrape] GRAPHQL_ERROR: scraper MindGeekAPI: could not unmarshal json from script output: EOF ['scrapeSingleScene']
2023-02-14 08:30:11
Error   
could not unmarshal json from script output: EOF
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI] TypeError: 'NoneType' object is not subscriptable
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]                               ~~~~~~~~~~~~~~~~~~~^^^^^^^^
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]     return_dict["duration"] = result["findScene"]["file"]["duration"]
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]   File "Z:\Stash\scrapers\MindGeekAPI.py", line 216, in graphql_getScene
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]     stash_scene_info = graphql_getScene(SCENE_ID)
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]   File "Z:\Stash\scrapers\MindGeekAPI.py", line 356, in scraping_json
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]     scraped_json = scraping_json(api_scene_json, SCENE_URL)
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI]   File "Z:\Stash\scrapers\MindGeekAPI.py", line 448, in <module>
2023-02-14 08:30:11
Error   
[Scrape / MindGeekAPI] Traceback (most recent call last):

**Comment by stg-annon** [comment]
so I'm finally able to get around to looking at this again, not entirely sure about the errors you are getting from the querys, they seem to be errors directly from stash which may have to do with your DB I've got the current version of the plugin/library running on 0.19.1 without the errors you're getting

I'm probably going to deprecate some features of this plugin as I've basically abandoned it after the Identify task was introduced as it is a better way of doing what most of this plugin does, however there is still a use case for it for Movies/Galleries so I'll focus around those

**Comment by cloudstrife112** [comment]
Ok thanks for trying to fix this problem, the stashbulkscrape has been working fine.  I dont think its about my db. Somehow when I use this scraper it works fine : https://github.com/niemands/StashPlugins (bulk_url_scraper). but I like stashbulkscrape more.  When I scrape these scenes by hand, 1by1. it works/ can it have something to do with python version?

I still getting these: 23-02-22 10:47:45
Error   
Plugin returned error: exit status 1
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape] AttributeError: 'StashInterface' object has no attribute 'list_scrapers'. Did you mean: 'reload_scrapers'?
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]              ^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]     for s in self.stash.list_scrapers(config.FRAGMENT_SCRAPE):
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]   File "Y:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 224, in list_all_fragment_tags
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]     for tag_name, types_tuple in self.list_all_fragment_tags().items():
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]   File "Y:\Stash\plugins\StashBulkScrape-main\utils\bulk_scrape.py", line 144, in bulk_fragment_scrape
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]     scraper.bulk_fragment_scrape()
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]   File "Y:\Stash\plugins\StashBulkScrape-main/main.py", line 43, in main
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]     main()
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape]   File "Y:\Stash\plugins\StashBulkScrape-main/main.py", line 57, in <module>
2023-02-22 10:47:45
Error   
[Plugin / Bulk Scrape] Traceback (most recent call last):
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] Variables: {'filter': {'per_page': 1000, 'q': '', 'page': 1}, 'scene_filter': {'tags': {'value': ['5270'], 'depth': 0, 'modifier': 'INCLUDES'}, 'url': {'value': '', 'modifier': 'NOT_NULL'}}}
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] }
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] scenes { id }
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] scene_count
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] back_image_path
2023-02-22 10:47:44
Error   
[Plugin / Bulk Scrape] front_image_path

**Comment by stg-annon** [comment]
that error specifically would be to do with an older version of the `stashapi` that does not have `list_scrapers()` which was reintroduced when working through bugs

I would suggest using a combination of the [Identify](https://docs.stashapp.cc/in-app-manual/tasks/identify/) task with the [ScrapeWithURL](https://github.com/stashapp/CommunityScrapers/blob/master/scrapers/ScrapeWithURL.yml) fragment scraper with the current version of stash as it allows you to customize the affected fields and would be better supported going forward for this use case

**Comment by cloudstrife112** [comment]
How does [ScrapeWithURL] works. can this be run in bulk? 
I have stashapi newer version from your github. I had reinstalled windows, thats why i had the older version again. somehow it works now for fragment scraping. Didnt change anything. Thanks for this.

**Comment by stg-annon** [comment]
so the `GRAPHQL_ERROR: must not be null` errors are likely from a malformed DB which is why a reinstall fixed the issue
